In [126]:
#SciPy:- SciPy stands for Scientific Python, SciPy is a open-source library that is used for scientific computing, 
#mathematics, science and engineering, etc.


In [127]:
import scipy
print(scipy.__version__)

1.6.1


In [128]:
#Constants:- SciPy more focused on scientic computation, it provide various built-in constants that is mainly 
#used in data science projects.

In [129]:
from scipy import constants
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [130]:
constants.pi

3.141592653589793

In [131]:
#Time constants
from scipy import constants
constants.minute

60.0

In [132]:
constants.day

86400.0

In [133]:
constants.year

31536000.0

In [134]:
constants.day


86400.0

In [135]:
constants.week

604800.0

In [136]:
#Optimize:- Optimize in Python is the set of procedures define in the SciPy package.
#That is basically used to find the value of the functin and root of the function.

In [179]:
from scipy import optimize
print(dir(optimize))

['BFGS', 'Bounds', 'HessianUpdateStrategy', 'LbfgsInvHessProduct', 'LinearConstraint', 'NonlinearConstraint', 'OptimizeResult', 'OptimizeWarning', 'RootResults', 'SR1', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__nnls', '__package__', '__path__', '__spec__', '_basinhopping', '_bglu_dense', '_cobyla', '_constraints', '_differentiable_functions', '_differentialevolution', '_dual_annealing', '_group_columns', '_hessian_update_strategy', '_highs', '_lbfgsb', '_linprog', '_linprog_doc', '_linprog_highs', '_linprog_ip', '_linprog_rs', '_linprog_simplex', '_linprog_util', '_lsap', '_lsap_module', '_lsq', '_minimize', '_minpack', '_nnls', '_numdiff', '_qap', '_remove_redundancy', '_root', '_root_scalar', '_shgo', '_shgo_lib', '_slsqp', '_spectral', '_trlib', '_trustregion', '_trustregion_constr', '_trustregion_dogleg', '_trustregion_exact', '_trustregion_krylov', '_trustregion_ncg', '_zeros', 'anderson', 'approx_fprime', 'basinhopping', 'bisect'

In [139]:
# Sparse Data:- Sparse data is a data where most of the item values are zero.
# Dense Data:- Dense data is a data where most of the item values are not zero.
# To work with sparse data, we need to import scipy.sparse module from scipy python library.

# Thare are two types of sparse matrix available in scipy.

# CSC:- Compressed Sparse Column, It is for efficient column and fast column slicing.
# CSR:- Compressed Sparse Rows, For fast row slicing, faster matrix vector products.

In [140]:
from scipy import sparse
print(dir(sparse))


['SparseEfficiencyWarning', 'SparseWarning', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_csparsetools', '_index', '_matrix_io', '_sparsetools', '_warnings', 'base', 'block_diag', 'bmat', 'bsr', 'bsr_matrix', 'compressed', 'construct', 'coo', 'coo_matrix', 'csc', 'csc_matrix', 'csgraph', 'csr', 'csr_matrix', 'data', 'dia', 'dia_matrix', 'diags', 'dok', 'dok_matrix', 'extract', 'eye', 'find', 'hstack', 'identity', 'issparse', 'isspmatrix', 'isspmatrix_bsr', 'isspmatrix_coo', 'isspmatrix_csc', 'isspmatrix_csr', 'isspmatrix_dia', 'isspmatrix_dok', 'isspmatrix_lil', 'kron', 'kronsum', 'lil', 'lil_matrix', 'linalg', 'load_npz', 'rand', 'random', 'save_npz', 'spdiags', 'spmatrix', 'sputils', 'test', 'tril', 'triu', 'vstack']


In [141]:
import numpy as np
array = np.array([1, 0, 0, 0, 2, 5, 7, 0, 0, 0])
print(array)

[1 0 0 0 2 5 7 0 0 0]


In [142]:
#find csr matrix
csr_data = sparse.csr_matrix(array)
print(csr_data)

  (0, 0)	1
  (0, 4)	2
  (0, 5)	5
  (0, 6)	7


In [143]:
# In above example (0, 4) represent the row and position of the item in rows. For example, 0 indicate the row, 4 indicate the 
# position of 1 in rows. Index always start with 0.

In [144]:
# Access non zero values by using data property.
csr_data.data

array([1, 2, 5, 7])

In [145]:
#count non zeros
csr_data.count_nonzero()

4

In [146]:
# Find the maximum item
csr_data.max()

7

In [147]:
# Find the minimum item
csr_data.min()

0

In [148]:
#find the mean of the array
csr_data.mean()

1.5

In [149]:
# Finf the sum of total non zero numbers
csr_data.sum()

15

In [150]:
#Find the transpose of the rows by using transpose() method
trans = csr_data.transpose()
print(trans)

  (0, 0)	1
  (4, 0)	2
  (5, 0)	5
  (6, 0)	7


In [151]:
#Find the square root of each item of the array
my_data = csr_data.sqrt()
print(my_data)

  (0, 0)	1.0
  (0, 4)	1.4142135623730951
  (0, 5)	2.23606797749979
  (0, 6)	2.6457513110645907


In [152]:
# Find the power of each item of the array 
my_data = csr_data.power(4)
print(my_data)

  (0, 0)	1
  (0, 4)	16
  (0, 5)	625
  (0, 6)	2401


In [153]:
my_data = csr_data.sin()
print(my_data)

  (0, 0)	0.8414709848078965
  (0, 4)	0.9092974268256817
  (0, 5)	-0.9589242746631385
  (0, 6)	0.6569865987187891


In [154]:
# Remove all the zeros from the array
csr_data.eliminate_zeros()

In [155]:
print(csr_data)

  (0, 0)	1
  (0, 4)	2
  (0, 5)	5
  (0, 6)	7


In [156]:
# Another Array
array1 = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
print(array1)

[[0 0 0]
 [0 0 1]
 [1 0 2]]


In [157]:
# Eliminate all the zeros from the matrix
csr_data2 = sparse.csr_matrix(array1)
print(csr_data2)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [158]:
# Converting from csr to csc using tocsc() method.
csc_data = sparse.csr_matrix(array1).tocsc()
print(csc_data)

  (2, 0)	1
  (1, 2)	1
  (2, 2)	2


In [159]:
# coo_matrix:- coo_matrix stands for coordinate matrix.
arr1 = sparse.coo_matrix([[1,2,3], [4,5,6], [7,8,9]]).toarray()
#find the shape of the matrix
arr1.shape

(3, 3)

In [160]:
# find the type of the matrix
arr1.dtype

dtype('int64')

In [161]:
# Array
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
arr2 = sparse.coo_matrix([[4, 5],[7, 8],[10, 11]]).toarray()

In [163]:
arr2.shape

(3, 2)

In [173]:
from scipy.sparse import coo_matrix, hstack, vstack
A = coo_matrix([[1, 2, 3], [3, 4, 5]])
B = coo_matrix([[4], [6]])

# Stack the sparse data horizontally...
hstack([A,B]).toarray()

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [175]:
A = coo_matrix([[1, 2], [3, 4]])
B = coo_matrix([[5, 6]])

# Stack the sparse data vertically...
vstack([A, B]).toarray()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [176]:
# Graph
from scipy.sparse import csgraph

In [178]:
# All the properties and method of the csgraph module
print(dir(csgraph))

['NegativeCycleError', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_flow', '_laplacian', '_matching', '_min_spanning_tree', '_reordering', '_shortest_path', '_tools', '_traversal', '_validation', 'bellman_ford', 'breadth_first_order', 'breadth_first_tree', 'connected_components', 'construct_dist_matrix', 'csgraph_from_dense', 'csgraph_from_masked', 'csgraph_masked_from_dense', 'csgraph_to_dense', 'csgraph_to_masked', 'depth_first_order', 'depth_first_tree', 'dijkstra', 'floyd_warshall', 'johnson', 'laplacian', 'maximum_bipartite_matching', 'maximum_flow', 'min_weight_full_bipartite_matching', 'minimum_spanning_tree', 'reconstruct_path', 'reverse_cuthill_mckee', 'shortest_path', 'structural_rank', 'test']


In [181]:
print(dir())

['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']


In [203]:
# Root finding
from math import sin
def equ(x):
    return x + sin(x)
    
value = optimize.root(equ, 90)
print(value.x)

[0.]


In [200]:
def equ(x):
    return x**2 - 4 
    
value = optimize.root(equ, [2,-2])
print(value.x)

[ 2. -2.]


In [219]:
def equ(x):
    return 2*x**2 - 12*x + 16
    
value = optimize.root(equ, [2,4])
print(value.x)

[2. 4.]


In [220]:
# minimize_scalar is used to used to minimize a function of one variable and many variables.
def scaler(x):
    return 3 * x ** 4 - 2 * x + 1

In [225]:
res = optimize.minimize_scalar(scaler)
print(res.x)

0.5503212087491959
